def build(bld):
    all_modules = [mod[len("ns3-"):] for mod in bld.env['NS3_ENABLED_MODULES']]
    obj = bld.create_ns3_program('ndn-cnmr', all_modules)
    obj.source = ['ndn-cnmr.cc',
                  'cnmr/cc.cc',
                  'cnmr/monitor-app.cc']
