## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    all_modules = [mod[len("ns3-"):] for mod in bld.env['NS3_ENABLED_MODULES']]
    obj = bld.create_ns3_program('monitor-app', all_modules)
    obj.source = 'monitor-app.cc'
